import type { LucideBuildParams, LucideIconData } from "@lucide/icons";
import { buildLucideSvg } from "@lucide/icons/build";
import { lucideDynamicIconImports, type LucideIconName } from "@lucide/icons/dynamic";
import type { IconName } from "@party-stack/icons";

export const lucideIconNames = {
    activity: "activity",
    add: "plus",
    airplane: "plane",
    alarm: "alarm-clock",
    alert: "triangle-alert",
    archive: "archive",
    "arrow-down": "arrow-down",
    "arrow-left": "arrow-left",
    "arrow-right": "arrow-right",
    "arrow-up": "arrow-up",
    attachment: "paperclip",
    award: "award",
    bank: "landmark",
    barcode: "barcode",
    bell: "bell",
    book: "book-open",
    bookmark: "bookmark",
    briefcase: "briefcase",
    bug: "bug",
    building: "building-2",
    calculator: "calculator",
    calendar: "calendar",
    camera: "camera",
    "chart-bar": "chart-bar",
    "chart-line": "chart-line",
    "chart-pie": "chart-pie",
    chat: "message-circle",
    check: "check",
    "check-circle": "circle-check",
    "chevron-down": "chevron-down",
    "chevron-left": "chevron-left",
    "chevron-right": "chevron-right",
    "chevron-up": "chevron-up",
    circle: "circle",
    clipboard: "clipboard",
    clock: "clock",
    cloud: "cloud",
    code: "code",
    compass: "compass",
    copy: "copy",
    "credit-card": "credit-card",
    cube: "box",
    database: "database",
    delete: "trash-2",
    document: "file",
    download: "download",
    edit: "pencil",
    email: "mail",
    error: "circle-x",
    eye: "eye",
    "eye-off": "eye-off",
    filter: "funnel",
    flag: "flag",
    folder: "folder",
    globe: "globe",
    grid: "grid-2x2",
    heart: "heart",
    help: "circle-help",
    history: "history",
    home: "house",
    image: "image",
    info: "info",
    key: "key",
    layers: "layers",
    lightbulb: "lightbulb",
    link: "link",
    list: "list",
    location: "map-pin",
    lock: "lock",
    "lock-open": "lock-open",
    map: "map",
    menu: "menu",
    microphone: "mic",
    minus: "minus",
    "minus-circle": "circle-minus",
    moon: "moon",
    "more-horizontal": "ellipsis",
    "more-vertical": "ellipsis-vertical",
    notification: "bell",
    package: "package",
    pause: "pause",
    people: "users",
    person: "user",
    phone: "phone",
    pin: "pin",
    play: "play",
    "play-circle": "circle-play",
    "plus-circle": "circle-plus",
    printer: "printer",
    project: "folder-kanban",
    refresh: "refresh-cw",
    rocket: "rocket",
    save: "save",
    search: "search",
    send: "send",
    settings: "settings",
    share: "share-2",
    shield: "shield",
    "shopping-bag": "shopping-bag",
    "shopping-cart": "shopping-cart",
    star: "star",
    stop: "square",
    sun: "sun",
    tag: "tag",
    ticket: "ticket",
    tools: "hammer",
    upload: "upload",
    video: "video",
    warning: "triangle-alert",
    window: "panels-top-left",
    wrench: "wrench",
    x: "x",
    "x-circle": "circle-x",
} as const satisfies Record<IconName, LucideIconName>;

export function getLucideIconName(name: IconName): LucideIconName {
    return lucideIconNames[name];
}

export async function loadLucideIcon(name: IconName): Promise<LucideIconData> {
    const module = await lucideDynamicIconImports[getLucideIconName(name)]();
    return module.default;
}

export async function getLucideSvg(name: IconName, params?: LucideBuildParams): Promise<string> {
    return buildLucideSvg(await loadLucideIcon(name), params);
}

export type { LucideBuildParams, LucideIconData, LucideIconName };
