/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QueryLabRouteImport } from './routes/query-lab'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as ApiRemoteOntologyEndpointRouteImport } from './routes/api.remote-ontology.$endpoint'

const QueryLabRoute = QueryLabRouteImport.update({
  id: '/query-lab',
  path: '/query-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoteOntologyEndpointRoute =
  ApiRemoteOntologyEndpointRouteImport.update({
    id: '/api/remote-ontology/$endpoint',
    path: '/api/remote-ontology/$endpoint',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/query-lab': typeof QueryLabRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/remote-ontology/$endpoint': typeof ApiRemoteOntologyEndpointRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/query-lab': typeof QueryLabRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/remote-ontology/$endpoint': typeof ApiRemoteOntologyEndpointRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/query-lab': typeof QueryLabRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/remote-ontology/$endpoint': typeof ApiRemoteOntologyEndpointRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/query-lab'
    | '/project/$projectId'
    | '/api/remote-ontology/$endpoint'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/query-lab'
    | '/project/$projectId'
    | '/api/remote-ontology/$endpoint'
  id:
    | '__root__'
    | '/'
    | '/query-lab'
    | '/project/$projectId'
    | '/api/remote-ontology/$endpoint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QueryLabRoute: typeof QueryLabRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  ApiRemoteOntologyEndpointRoute: typeof ApiRemoteOntologyEndpointRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/query-lab': {
      id: '/query-lab'
      path: '/query-lab'
      fullPath: '/query-lab'
      preLoaderRoute: typeof QueryLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remote-ontology/$endpoint': {
      id: '/api/remote-ontology/$endpoint'
      path: '/api/remote-ontology/$endpoint'
      fullPath: '/api/remote-ontology/$endpoint'
      preLoaderRoute: typeof ApiRemoteOntologyEndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QueryLabRoute: QueryLabRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  ApiRemoteOntologyEndpointRoute: ApiRemoteOntologyEndpointRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
